name: My Starter Workflow

on:
  workflow_dispatch:

jobs:
    steps:
      - uses: actions/checkout@v4

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy to your project.
  
   call-reusable-workflow:
      strategy:
        matrix:
          nodeversion: [14, 16, 18, 20]
      uses: ./.github/workflows/reusable-workflow.yml
      with:
        node: ${{ matrix.nodeversion }}
